In [1]:
from 工具 import *
import matplotlib.pyplot as plt;import matplotlib.font_manager
import re
碼表 = pd.read_excel('碼表.xlsx', '正表')
# 碼表.dropna(subset=["表頭意義參見：http://kanji-database.sourceforge.net/ids/ids-analysis.html"])

In [2]:
# 統計
plt.rcParams["font.family"] = "Noto Sans CJK JP", "KaiXinSongB"
# 式 = '⿳⿳⿰甲乙丙丁戊己';檢構字式(式)
碼表.fillna('',inplace=True)
所有構件 = 碼表['迩原正解'].str.cat(sep='') + 碼表['迩原或解'].astype(str).str.cat(sep='') + 碼表['迩原別解'].astype(str).str.cat(sep='') + 碼表['迩原又解'].astype(str).str.cat(sep='')
所有部件 = re.sub('['+(''.join(冓.keys()))+']','',所有構件)
計 = Counter(所有部件)
# plt.figure(dpi=100).set_figwidth(300)
# plt.bar(*zip(*計.most_common()), width=4)
# plt.show()
# plt.figure().get_dpi()
# 系統字型列 = matplotlib.font_manager.findSystemFonts(fontpaths=None)# https://matplotlib.org/stable/api/font_manager_api.html
# 字型列 = matplotlib.font_manager.get_font_names()
# matplotlib.font_manager.FontProperties('YeMing').get_name()
# print(系統字型列)

In [9]:
覈 = 碼表["迩原正解"].apply(lambda z: 檢構字式(z,))
碼表["迩原正解"].loc[覈!=1]

　⿹ 2 件
　 又 4 [1]
　 一 5 [2]
　⿹又一→☯
　⿲ 3 件
　 十 3 [1]
　 十 4 [2]
　 十 5 [3]
　⿲十十十→☯
　⿰ 2 件
　 人 3 [1]
　 人 4 [2]
　⿰人人→☯
　⿶ 2 件
　 卩 3 [1]
　 凵 4 [2]
　⿶卩凵→☯
　⿵ 2 件
　 大 4 [1]
　 凵 5 [2]
　⿵大凵→☯
　⿵ 2 件
　 大 4 [1]
　 凵 5 [2]
　⿵大凵→☯
　⿰ 2 件
　 大 3 [1]
　 大 4 [2]
　⿰大大→☯
　Ｔ 3 件
　 桑 3 [1]
　 口 4 [2]
　 口 5 [3]
　Ｔ桑口口→☯
　⿱ 2 件
　　⿸ 2 件
　　 人 5 [1]
　　 丶 6 [2]
　　⿸人丶→☯
　 ☯ 6 [1]
　 ∞ 7 [2]
　⿱☯∞→☯
　⿰ 2 件
　 人 4 [1]
　 人 5 [2]
　⿰人人→☯
　⿲ 3 件
　 白 3 [1]
　 幺 4 [2]
　 幺 5 [3]
　⿲白幺幺→☯
　⿰ 2 件
　 夂 4 [1]
　 㐄 5 [2]
　⿰夂㐄→☯
　⿰ 2 件
　 夂 4 [1]
　 㐄 5 [2]
　⿰夂㐄→☯
　⿴ 2 件
　 口 4 [1]
　 一 5 [2]
　⿴口一→☯
　⿱ 2 件
　 爪 3 [1]
　 子 4 [2]
　⿱爪子→☯
　⿱ 2 件
　 爪 3 [1]
　 糸 4 [2]
　⿱爪糸→☯
　∃ 2 件
　 倝 3 [1]
　 干 4 [2]
　∃倝干→☯
　⿳ 3 件
　 爪 3 [1]
　　⿻ 2 件
　　 幺 5 [1]
　　 冂 6 [2]
　　⿻幺冂→☯
　 ☯ 6 [2]
　 又 7 [3]
　⿳爪☯又→☯
　⿻ 2 件
　 又 4 [1]
　 亅 5 [2]
　⿻又亅→☯
　⿰ 2 件
　 止 3 [1]
　 匕 4 [2]
　⿰止匕→☯
　⿱ 2 件
　 一 4 [1]
　 一 5 [2]
　⿱一一→☯
　⿲ 3 件
　 人 4 [1]
　 口 5 [2]
　 又 6 [3]
　⿲人口又→☯
　⿻ 2 件
　 亅 4 [1]
　 一 5 [2]
　⿻亅一→☯
　⿰ 2 件
　　⿱ 2 件
　　 木 5 [1]
　　 土 6 [2]
　　⿱木土→☯
　 ☯ 6 [1]
　 丮 7 [2]
　⿰☯丮→☯
　⿱ 2 件
　 日 4 [1]
　 ● 5 [2]
　⿱日●→☯
　Ｙ 3 件
　 爪 4 [1]
　 仉 5 [2]
　 亚 6 [3]
　Ｙ爪仉亚→☯
　⿱ 2 件
　 一 4 [1]
　 一 5 [2]
　⿱一一→☯
　⿹ 2 件
　 又 4 [1]
　 一 5 [2]
　⿹又一→☯
　⿶ 2 件
　 丶 4 [1]
　 乂 5 [2]
　⿶丶乂→☯
　⿱ 2 件
　 冂 4 [1]
　 人 5 [2]
　⿱冂人→☯
　⿱ 2 件
　 又 4 [1]
　 又 5 [2]
　⿱又又→☯
　⿴ 2 件
　 口 5 [1]
　 一 6 [2]
　⿴口一→☯
　⿱ 2 件
　 目 4 [1]
　 卩 5 [2]
　⿱目卩→☯
　⿱ 2 件
　 亠 4 [1]
　 力 5 [2]
　⿱亠力→☯
　⿱ 2 件
　 大 4 [1]
　 一 5 [2]
　⿱大一→☯
　⿱ 2 件
　 二 4 [1]
　 女 5 [2]
　⿱二女→☯
　⿰ 2 件
　 口 4 [1]
　 口 5 [2]
　⿰口口→☯
　⿰ 2 件
　 人 7 [1]
　 人 8 [2]
　⿰人人→☯
　⿱ 2 件
　 ● 4 [1]
　 止 5 [2]
　⿱●止→☯
　⿱ 2 件
　 目 4 [1]
　 匕 5 [2]
　⿱目匕→☯
　⿱ 2 件
　 氒 4 [1]
　 口 5 [2]
　⿱氒口→☯
　⿱ 2 件
　 八 4 [1]
　 肉 5 [2]
　⿱八肉→☯
　⿰ 2 件
　 井 4 [1]
　 刀 5 [2]
　⿰井刀→☯
　⿱ 2 件
　 口 4 [1]
　 川 5 [2]
　⿱口川→☯
　⿱ 2 件
　 ⼣ 4 [1]
　 ⼣ 5 [2]
　⿱⼣⼣→☯
　Ｔ 3 件
　 大 4 [1]
　 匕 5 [2]
　 人 6 [3]
　Ｔ大匕人→☯
　⿱ 2 件
　 卜 4 [1]
　 鼎 5 [2]
　⿱卜鼎→☯
　⿱ 2 件
　 夭 4 [1]
　 八 5 [2]
　⿱夭八→☯
　⿸ 2 件
　 厂 4 [1]
　 矢 5 [2]
　⿸厂矢→☯
　⿰ 2 件
　 丑 4 [1]
　 刀 5 [2]
　⿰丑刀→☯
　⿱ 2 件
　 𭘒 4 [1]
　 又 5 [2]
　⿱𭘒又→☯
　⿳ 3 件
　 八 4 [1]
　 口 5 [2]
　 人 6 [3]
　⿳八口人→☯
　⿱ 2 件
　 卞 4 [1]
　 又 5 [2]
　⿱卞又→☯
　⿱ 2 件
　 允 4 [1]
　 夂 5 [2]
　⿱允夂→☯
　⿱ 2 件
　 目 4 [1]
　 卩 5 [2]
　⿱目卩→☯
　⿻ 2 件
　 子 4 [1]
　 八 5 [2]
　⿻子八→☯
　⿱ 2 件
　 攴 4 [1]
　 彡 5 [2]
　⿱攴彡→☯
　⿳ 3 件
　 耂 4 [1]
　 𠃬 5 [2]
　　⿰ 2 件
　　 口 7 [1]
　　　⿹ 2 件
　　　 又 9 [1]
　　　 一 10 [2]
　　　⿹又一→☯
　　 ☯ 10 [2]
　　⿰口☯→☯
　 ☯ 10 [3]
　⿳耂𠃬☯→☯
　⿲ 3 件
　 人 3 [1]
　 丨 4 [2]
　 攴 5 [3]
　⿲人丨攴→☯
　⿵ 2 件
　　Ｔ 3 件
　　 丰 5 [1]
　　 𠂇 6 [2]
　　 又 7 [3]
　　Ｔ丰𠂇又→☯
　 ☯ 7 [1]
　 手 8 [2]
　⿵☯手→☯
　⿱ 2 件
　　⿺ 2 件
　　 夂 5 [1]
　　 人 6 [2]
　　⿺夂人→☯
　 ☯ 6 [1]
　 口 7 [2]
　⿱☯口→☯
　⿱ 2 件
　　⿱ 2 件
　　 㐅 5 [1]
　　 㐅 6 [2]
　　⿱㐅㐅→☯
　 ☯ 6 [1]
　 肉 7 [2]
　⿱☯肉→☯
　⿱ 2 件
　 一 4 [1]
　 㒳 5 [2]
　⿱一㒳→☯
　⿱ 2 件
　 宀 4 [1]
　 夗 5 [2]
　⿱宀夗→☯
　⿸ 2 件
　 戶 4 [1]
　 口 5 [2]
　⿸戶口→☯
　⿳ 3 件
　 八 4 [1]
　 厶 5 [2]
　 心 6 [3]
　⿳八厶心→☯
　⿴ 2 件
　 囗 4 [1]
　　⿱ 2 件
　　 ⼗ 6 [1]
　　 口 7 [2]
　　⿱⼗口→☯
　 ☯ 7 [2]
　⿴囗☯→☯
　⿱ 2 件
　 宀 4 [1]
　 𠂤 5 [2]
　⿱宀𠂤→☯
　⿳ 3 件
　 一 4 [1]
　 不 5 [2]
　 口 6 [3]
　⿳一不口→☯
　⿱ 2 件
　 冊 4 [1]
　　⿰ 2 件
　　 𠂇 6 [1]
　　 又 7 [2]
　　⿰𠂇又→☯
　 ☯ 7 [2]
　⿱冊☯→☯
　⿱ 2 件
　 十 4 [1]
　　⿺ 2 件
　　 目 6 [1]
　　 乚 7 [2]
　　⿺目乚→☯
　 ☯ 7 [2]
　⿱十☯→☯
　⿱ 2 件
　 大 4 [1]
　 示 5 [2]
　⿱大示→☯
　⿳ 3 件
　 亼 4 [1]
　 口 5 [2]
　　⿰ 2 件
　　 人 7 [1]
　　 人 8 [2]
　　⿰人人→☯
　 ☯ 8 [3]
　⿳亼口☯→☯
　⿰ 2 件
　 牙 4 [1]
　　⿱ 2 件
　　 囗 6 [1]
　　 卩 7 [2]
　　⿱囗卩→☯
　 ☯ 7 [2]
　⿰牙☯→☯
　⿰ 2 件
　 言 4 [1]
　 者 5 [2]
　⿰言者→☯
　⿰ 2 件
　 又 4 [1]
　 隹 5 [2]
　⿰又隹→☯
　⿱ 2 件
　 亠 4 [1]
　 昜 5 [2]
　⿱亠昜→☯
　⿳ 3 件
　 囟 4 [1]
　 人 5 [2]
　 夂 6 [3]
　⿳囟人夂→☯
　⿱ 2 件
　 堇 4 [1]
　 火 5 [2]
　⿱堇火→☯
　⿰ 2 件
　 口 4 [1]
　 口 5 [2]
　⿰口口→☯
　⿰ 2 件
　 人 7 [1]
　 人 8 [2]
　⿰人人→☯
　⿱ 2 件
　 㬰 4 [1]
　 貝 5 [2]
　⿱㬰貝→☯
　⿱ 2 件
　　⿰ 2 件
　　　⿻ 2 件
　　　 一 6 [1]
　　　 大 7 [2]
　　　⿻一大→☯
　　 ☯ 7 [1]
　　　⿻ 2 件
　　　 一 9 [1]
　　　 大 10 [2]
　　　⿻一大→☯
　　 ☯ 10 [2]
　　⿰☯☯→☯
　 ☯ 10 [1]
　　⿴ 2 件
　　 口 12 [1]
　　 一 13 [2]
　　⿴口一→☯
　 ☯ 13 [2]
　⿱☯☯→☯
　⿰ 2 件
　 朿 3 [1]
　 朿 4 [2]
　⿰朿朿→☯
　⿱ 2 件
　　⿲ 3 件
　　 囟 5 [1]
　　 爪 6 [2]
　　 仉 7 [3]
　　⿲囟爪仉→☯
　 ☯ 7 [1]
　　⿰ 2 件
　　 夂 9 [1]
　　 㐄 10 [2]
　　⿰夂㐄→☯
　 ☯ 10 [2]
　⿱☯☯→☯
　⿱ 2 件
　 音 4 [1]
　 心 5 [2]
　⿱音心→☯
　⿳ 3 件
　　⿻ 2 件
　　 囟 5 [1]
　　　⸬ 1 件
　　　 丶 7 [1]
　　　⸬丶→☯
　　 ☯ 7 [2]
　　⿻囟☯→☯
　 ☯ 7 [1]
　 人 8 [2]
　 夂 9 [3]
　⿳☯人夂→☯
　⿳ 3 件
　 屯 4 [1]
　 罒 5 [2]
　 貝 6 [3]
　⿳屯罒貝→☯
　⿰ 2 件
　 青 4 [1]
　　⿱ 2 件
　　 目 6 [1]
　　 卩 7 [2]
　　⿱目卩→☯
　 ☯ 7 [2]
　⿰青☯→☯
　⿱ 2 件
　 艸 4 [1]
　 為 5 [2]
　⿱艸為→☯
　⿰ 2 件
　 言 4 [1]
　 者 5 [2]
　⿰言者→☯
　⿲ 3 件
　 人 3 [1]
　 丨 4 [2]
　 攴 5 [3]
　⿲人丨攴→☯
　⿵ 2 件
　　⿻ 2 件
　　 宀 4 [1]
　　 八 5 [2]
　　⿻宀八→☯
　 ☯ 5 [1]
　 口 6 [2]
　⿵☯口→☯
　⿰ 2 件
　 屮 3 [1]
　 屮 4 [2]
　⿰屮屮→☯
　⿰ 2 件
　 𠂇 4 [1]
　 又 5 [2]
　⿰𠂇又→☯
　⿱ 2 件
　 ● 4 [1]
　 大 5 [2]
　⿱●大→☯
　⿰ 2 件
　 𠂇 4 [1]
　 又 5 [2]
　⿰𠂇又→☯
　⿰ 2 件
　 𠂇 4 [1]
　 又 5 [2]
　⿰𠂇又→☯
　⿰ 2 件
　 𠂇 4 [1]
　 又 5 [2]
　⿰𠂇又→☯
　⿰ 2 件
　 幺 3 [1]
　 幺 4 [2]
　⿰幺幺→☯
　⿰ 2 件
　 口 4 [1]
　 匕 5 [2]
　⿰口匕→☯
　⿱ 2 件
　 亼 4 [1]
　 八 5 [2]
　⿱亼八→☯
　⿰ 2 件
　 禾 3 [1]
　 禾 4 [2]
　⿰禾禾→☯
　Ｙ 3 件
　 𠂇 4 [1]
　 又 5 [2]
　 大 6 [3]
　Ｙ𠂇又大→☯
　Ｙ 3 件
　 𠂇 4 [1]
　 又 5 [2]
　 大 6 [3]
　Ｙ𠂇又大→☯
　⿱ 2 件
　 八 4 [1]
　 口 5 [2]
　⿱八口→☯
　⿲ 3 件
　 田 3 [1]
　 爪 4 [2]
　 仉 5 [3]
　⿲田爪仉→☯
　⿱ 2 件
　 冃 3 [1]
　　⿱ 2 件
　　 一 5 [1]
　　 人 6 [2]
　　⿱一人→☯
　 ☯ 6 [2]
　⿱冃☯→☯
　⿹ 2 件
　 又 8 [1]
　 一 9 [2]
　⿹又一→☯
　⿰ 2 件
　 耳 4 [1]
　 又 5 [2]
　⿰耳又→☯
　⿱ 2 件
　 元 4 [1]
　 攴 5 [2]
　⿱元攴→☯
　⿰ 2 件
　 木 4 [1]
　 木 5 [2]
　⿰木木→☯
　▤ 4 件
　 冖 3 [1]
　 艸 4 [2]
　 日 5 [3]
　 六 6 [4]
　▤冖艸日六→☯
　⿱ 2 件
　 丶 3 [1]
　 丶 4 [2]
　⿱丶丶→☯
　⿱ 2 件
　 口 6 [1]
　 人 7 [2]
　⿱口人→☯
　⿱ 2 件
　 𱍸 4 [1]
　 口 5 [2]
　⿱𱍸口→☯
　⿳ 3 件
　 屯 4 [1]
　 罒 5 [2]
　 貝 6 [3]
　⿳屯罒貝→☯
　⿰ 2 件
　 人 3 [1]
　 壬 4 [2]
　⿰人壬→☯
　⿱ 2 件
　 丿 4 [1]
　 日 5 [2]
　⿱丿日→☯
　⿱ 2 件
　　⿰ 2 件
　　 𣥂 4 [1]
　　 止 5 [2]
　　⿰𣥂止→☯
　 ☯ 5 [1]
　 豆 6 [2]
　⿱☯豆→☯
　⿱ 2 件
　 大 3 [1]
　 凵 4 [2]
　⿱大凵→☯
　⿱ 2 件
　 大 3 [1]
　 凵 4 [2]
　⿱大凵→☯
　⿱ 2 件
　 氒 3 [1]
　 口 4 [2]
　⿱氒口→☯
　⿳ 3 件
　 一 3 [1]
　 月 4 [2]
　 一 5 [3]
　⿳一月一→☯
　⿱ 2 件
　 𢆉 3 [1]
　 一 4 [2]
　⿱𢆉一→☯
　⿳ 3 件
　 屮 3 [1]
　 一 4 [2]
　 亇 5 [3]
　⿳屮一亇→☯
　⿸ 2 件
　 尸 3 [1]
　 巾 4 [2]
　⿸尸巾→☯
　⿱ 2 件
　 釆 3 [1]
　　⿰ 2 件
　　 𠂇 5 [1]
　　 又 6 [2]
　　⿰𠂇又→☯
　 ☯ 6 [2]
　⿱釆☯→☯
　⿱ 2 件
　 大 3 [1]
　 凵 4 [2]
　⿱大凵→☯
　⿱ 2 件
　 小 3 [1]
　 月 4 [2]
　⿱小月→☯
　⿻ 2 件
　 禾 3 [1]
　 口 4 [2]
　⿻禾口→☯
　⿱ 2 件
　 止 3 [1]
　 舟 4 [2]
　⿱止舟→☯
　⿱ 2 件
　 戈 3 [1]
　 戈 4 [2]
　⿱戈戈→☯
　⿱ 2 件
　 圭 3 [1]
　 石 4 [2]
　⿱圭石→☯
　⿸ 2 件
　　⿱ 2 件
　　 止 4 [1]
　　 舟 5 [2]
　　⿱止舟→☯
　 ☯ 5 [1]
　 刀 6 [2]
　⿸☯刀→☯
　⿸ 2 件
　　⿱ 2 件
　　 丶 4 [1]
　　 石 5 [2]
　　⿱丶石→☯
　 ☯ 5 [1]
　 又 6 [2]
　⿸☯又→☯
　⿱ 2 件
　 𫲸 3 [1]
　 口 4 [2]
　⿱𫲸口→☯
　⿳ 3 件
　　⿲ 3 件
　　 囟 4 [1]
　　 爪 5 [2]
　　 仉 6 [3]
　　⿲囟爪仉→☯
　 ☯ 6 [1]
　 一 7 [2]
　 火 8 [3]
　⿳☯一火→☯
　⿱ 2 件
　 虍 3 [1]
　 豕 4 [2]
　⿱虍豕→☯
　⿱ 2 件
　 卯 3 [1]
　 金 4 [2]
　⿱卯金→☯
　⿰ 2 件
　 肉 3 [1]
　 力 4 [2]
　⿰肉力→☯
　⿰ 2 件
　 女 3 [1]
　 又 4 [2]
　⿰女又→☯
　⿱ 2 件
　 大 3 [1]
　 凵 4 [2]
　⿱大凵→☯
　⿱ 2 件
　　⿰ 2 件
　　 火 4 [1]
　　 火 5 [2]
　　⿰火火→☯
　 ☯ 5 [1]
　 冖 6 [2]
　⿱☯冖→☯
　⿱ 2 件
　　⿰ 2 件
　　 火 4 [1]
　　 火 5 [2]
　　⿰火火→☯
　 ☯ 5 [1]
　 冖 6 [2]
　⿱☯冖→☯
　⿱ 2 件
　 釆 3 [1]
　　⿰ 2 件
　　 𠂇 5 [1]
　　 又 6 [2]
　　⿰𠂇又→☯
　 ☯ 6 [2]
　⿱釆☯→☯
　⿷ 2 件
　 匚 3 [1]
　 㞷 4 [2]
　⿷匚㞷→☯
　⿱ 2 件
　 丰 3 [1]
　 子 4 [2]
　⿱丰子→☯
　⿱ 2 件
　　⿻ 2 件
　　 人 4 [1]
　　 東 5 [2]
　　⿻人東→☯
　 ☯ 5 [1]
　 土 6 [2]
　⿱☯土→☯
　⿰ 2 件
　 𭿵 3 [1]
　 攴 4 [2]
　⿰𭿵攴→☯
　⿱ 2 件
　 公 3 [1]
　 羽 4 [2]
　⿱公羽→☯
　⿰ 2 件
　 舟 3 [1]
　　⿱ 2 件
　　　⿻ 2 件
　　　 八 6 [1]
　　　 十 7 [2]
　　　⿻八十→☯
　　 ☯ 7 [1]
　　　⿰ 2 件
　　　 𠂇 9 [1]
　　　 又 10 [2]
　　　⿰𠂇又→☯
　　 ☯ 10 [2]
　　⿱☯☯→☯
　 ☯ 10 [2]
　⿰舟☯→☯
　⿱ 2 件
　　⿰ 2 件
　　 火 4 [1]
　　 火 5 [2]
　　⿰火火→☯
　 ☯ 5 [1]
　 冖 6 [2]
　⿱☯冖→☯
　⿱ 2 件
　 一 4 [1]
　 一 5 [2]
　⿱一一→☯
　⿱ 2 件
　 一 4 [1]
　 一 5 [2]
　⿱一一→☯
　⿱ 2 件
　 亼 4 [1]
　 口 5 [2]
　⿱亼口→☯
　⿰ 2 件
　 身 4 [1]
　 弓 5 [2]
　⿰身弓→☯
　⿱ 2 件
　　⿰ 2 件
　　 屮 5 [1]
　　 屮 6 [2]
　　⿰屮屮→☯
　 ☯ 6 [1]
　　⿱ 2 件
　　 亼 8 [1]
　　 口 9 [2]
　　⿱亼口→☯
　 ☯ 9 [2]
　⿱☯☯→☯
　⿰ 2 件
　 皀 4 [1]
　 殳 5 [2]
　⿰皀殳→☯
　⿰ 2 件
　 身 4 [1]
　 吕 5 [2]
　⿰身吕→☯
　⿱ 2 件
　 彳 4 [1]
　 止 5 [2]
　⿱彳止→☯
　⿰ 2 件
　 車 4 [1]
　 九 5 [2]
　⿰車九→☯
　⿱ 2 件
　 勿 4 [1]
　 曰 5 [2]
　⿱勿曰→☯
　⿰ 2 件
　 車 4 [1]
　 九 5 [2]
　⿰車九→☯
　⿱ 2 件
　 㬰 4 [1]
　 貝 5 [2]
　⿱㬰貝→☯
　⿰ 2 件
　 水 4 [1]
　 隹 5 [2]
　⿰水隹→☯
　⿱ 2 件
　 㬰 4 [1]
　 貝 5 [2]
　⿱㬰貝→☯
　⿳ 3 件
　 屯 4 [1]
　 罒 5 [2]
　 貝 6 [3]
　⿳屯罒貝→☯
　⿱ 2 件
　 亼 4 [1]
　 口 5 [2]
　⿱亼口→☯
　⿱ 2 件
　 日 4 [1]
　 女 5 [2]
　⿱日女→☯
　⸫ 1 件
　 口 4 [1]
　⸫口→☯
　⿻ 2 件
　 力 4 [1]
　 八 5 [2]
　⿻力八→☯
　⿱ 2 件
　 止 3 [1]
　 凵 4 [2]
　⿱止凵→☯
　⿱ 2 件
　 冈 6 [1]
　 貝 7 [2]
　⿱冈貝→☯
　⿱ 2 件
　 人 3 [1]
　 厂 4 [2]
　⿱人厂→☯
　⿱ 2 件
　 𬼆 3 [1]
　 厶 4 [2]
　⿱𬼆厶→☯
　⿰ 2 件
　 𠂇 4 [1]
　 又 5 [2]
　⿰𠂇又→☯
　⿱ 2 件
　 午 3 [1]
　 止 4 [2]
　⿱午止→☯
　⿱ 2 件
　 𬼆 3 [1]
　 口 4 [2]
　⿱𬼆口→☯
　⿰ 2 件
　 口 4 [1]
　 匕 5 [2]
　⿰口匕→☯
　⿰ 2 件
　 鼎 4 [1]
　 刀 5 [2]
　⿰鼎刀→☯
　⿰ 2 件
　 口 4 [1]
　　⿸ 2 件
　　 广 6 [1]
　　 丁 7 [2]
　　⿸广丁→☯
　 ☯ 7 [2]
　⿰口☯→☯
　⿰ 2 件
　 鼎 4 [1]
　 刀 5 [2]
　⿰鼎刀→☯
　⿰ 2 件
　 禾 4 [1]
　 禾 5 [2]
　⿰禾禾→☯
　⿰ 2 件
　 屰 4 [1]
　 欠 5 [2]
　⿰屰欠→☯
　⿱ 2 件
　 日 4 [1]
　　⿱ 2 件
　　　⿺ 2 件
　　　 夂 7 [1]
　　　 人 8 [2]
　　　⿺夂人→☯
　　 ☯ 8 [1]
　　 口 9 [2]
　　⿱☯口→☯
　 ☯ 9 [2]
　⿱日☯→☯
　⿰ 2 件
　　⿱ 2 件
　　　⿴ 2 件
　　　 口 6 [1]
　　　 一 7 [2]
　　　⿴口一→☯
　　 ☯ 7 [1]
　　 肉 8 [2]
　　⿱☯肉→☯
　 ☯ 8 [1]
　 犬 9 [2]
　⿰☯犬→☯
　⿰ 2 件
　 尚 4 [1]
　 攴 5 [2]
　⿰尚攴→☯
　⿱ 2 件
　　⿰ 2 件
　　　⿱ 2 件
　　　　⿴ 2 件
　　　　 口 7 [1]
　　　　 一 8 [2]
　　　　⿴口一→☯
　　　 ☯ 8 [1]
　　　 肉 9 [2]
　　　⿱☯肉→☯
　　 ☯ 9 [1]
　　 犬 10 [2]
　　⿰☯犬→☯
　 ☯ 10 [1]
　 甲 11 [2]
　⿱☯甲→☯
　⸫ 1 件
　 〇 3 [1]
　⸫〇→☯
　⿳ 3 件
　 一 6 [1]
　 一 7 [2]
　 一 8 [3]
　⿳一一一→☯
　⸫ 1 件
　 〇 3 [1]
　⸫〇→☯
　⸫ 1 件
　 〇 3 [1]
　⸫〇→☯
　⸫ 1 件
　 〇 3 [1]
　⸫〇→☯
　⿳ 3 件
　 一 6 [1]
　 一 7 [2]
　 一 8 [3]
　⿳一一一→☯
　⸫ 1 件
　 〇 3 [1]
　⸫〇→☯
　⿱ 2 件
　 㤅 4 [1]
　 夂 5 [2]
　⿱㤅夂→☯
　⿺ 2 件
　 隶 4 [1]
　　⿱ 2 件
　　 彳 6 [1]
　　 止 7 [2]
　　⿱彳止→☯
　 ☯ 7 [2]
　⿺隶☯→☯
　Ｔ 3 件
　 言 3 [1]
　 糸 4 [2]
　 糸 5 [3]
　Ｔ言糸糸→☯
　⿱ 2 件
　 一 3 [1]
　　⿸ 2 件
　　 丆 5 [1]
　　　⿱ 2 件
　　　 一 7 [1]
　　　 一 8 [2]
　　　⿱一一→☯
　　 ☯ 8 [2]
　　⿸丆☯→☯
　 ☯ 8 [2]
　⿱一☯→☯
　⿱ 2 件
　 仉 10 [1]
　 又 11 [2]
　⿱仉又→☯
　⿸ 2 件
　 尸 3 [1]
　　⿳ 3 件
　　 一 5 [1]
　　 一 6 [2]
　　 火 7 [3]
　　⿳一一火→☯
　 ☯ 7 [2]
　⿸尸☯→☯
　⿵ 2 件
　 宀 3 [1]
　 火 4 [2]
　⿵宀火→☯
　⸫ 1 件
　 又 3 [1]
　⸫又→☯
　⿰ 2 件
　 歺 3 [1]
　 又 4 [2]
　⿰歺又→☯
　⿱ 2 件
　 𠔁 6 [1]
　 目 7 [2]
　⿱𠔁目→☯
　⿰ 2 件
　 耳 4 [1]
　 又 5 [2]
　⿰耳又→☯
　⿻ 2 件
　 又 3 [1]
　 丿 4 [2]
　⿻又丿→☯
　⿰ 2 件
　 弓 4 [1]
　 丿 5 [2]
　⿰弓丿→☯
　⿺ 2 件
　 子 4 [1]
　 乚 5 [2]
　⿺子乚→☯
　⿱ 2 件
　 艸 4 [1]
　 乙 5 [2]
　⿱艸乙→☯
　⿱ 2 件
　 口 4 [1]
　 卩 5 [2]
　⿱口卩→☯
　⿰ 2 件
　 口 4 [1]
　 卩 5 [2]
　⿰口卩→☯
　⿰ 2 件
　 人 4 [1]
　 它 5 [2]
　⿰人它→☯
　⿺ 2 件
　 夂 3 [1]
　 人 4 [2]
　⿺夂人→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿸ 2 件
　 又 4 [1]
　 巾 5 [2]
　⿸又巾→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿰ 2 件
　　⿱ 2 件
　　 丶 4 [1]
　　 丶 5 [2]
　　⿱丶丶→☯
　 ☯ 5 [1]
　 欠 6 [2]
　⿰☯欠→☯
　⿱ 2 件
　 艸 4 [1]
　 犬 5 [2]
　⿱艸犬→☯
　⿽ 2 件
　 才 3 [1]
　 戈 4 [2]
　⿽才戈→☯
　⿷ 2 件
　 匚 4 [1]
　 㞷 5 [2]
　⿷匚㞷→☯
　⿺ 2 件
　 大 4 [1]
　　⿱ 2 件
　　 彳 6 [1]
　　 止 7 [2]
　　⿱彳止→☯
　 ☯ 7 [2]
　⿺大☯→☯
　⿱ 2 件
　 止 4 [1]
　 夕 5 [2]
　⿱止夕→☯
　⿱ 2 件
　 化 4 [1]
　 十 5 [2]
　⿱化十→☯
　⿰ 2 件
　 口 3 [1]
　 匕 4 [2]
　⿰口匕→☯
　⿹ 2 件
　 𠀀 3 [1]
　 口 4 [2]
　⿹𠀀口→☯
　⿹ 2 件
　 𠀀 6 [1]
　 口 7 [2]
　⿹𠀀口→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿱ 2 件
　 目 4 [1]
　 卩 5 [2]
　⿱目卩→☯
　⿰ 2 件
　　⿱ 2 件
　　 屮 4 [1]
　　 亇 5 [2]
　　⿱屮亇→☯
　 ☯ 5 [1]
　 斤 6 [2]
　⿰☯斤→☯
　⿳ 3 件
　 爪 4 [1]
　 ● 5 [2]
　 寸 6 [3]
　⿳爪●寸→☯
　⿰ 2 件
　 戶 3 [1]
　 又 4 [2]
　⿰戶又→☯
　⿱ 2 件
　 來 4 [1]
　 夂 5 [2]
　⿱來夂→☯
　⿰ 2 件
　 口 4 [1]
　 匕 5 [2]
　⿰口匕→☯
　⿱ 2 件
　 工 4 [1]
　 貝 5 [2]
　⿱工貝→☯
　⿰ 2 件
　 口 4 [1]
　 匕 5 [2]
　⿰口匕→☯
　⿱ 2 件
　 小 4 [1]
　 貝 5 [2]
　⿱小貝→☯
　⿵ 2 件
　　Ｔ 3 件
　　 丰 5 [1]
　　 𠂇 6 [2]
　　 又 7 [3]
　　Ｔ丰𠂇又→☯
　 ☯ 7 [1]
　 手 8 [2]
　⿵☯手→☯
　⿱ 2 件
　 今 4 [1]
　 心 5 [2]
　⿱今心→☯
　⿱ 2 件
　 冊 4 [1]
　　⿰ 2 件
　　 𠂇 6 [1]
　　 又 7 [2]
　　⿰𠂇又→☯
　 ☯ 7 [2]
　⿱冊☯→☯
　⿰ 2 件
　　⿱ 2 件
　　 爪 5 [1]
　　 子 6 [2]
　　⿱爪子→☯
　 ☯ 6 [1]
　 乚 7 [2]
　⿰☯乚→☯
　⿻ 2 件
　 豕 4 [1]
　 丶 5 [2]
　⿻豕丶→☯
　⿱ 2 件
　 ⾟ 3 [1]
　 丙 4 [2]
　⿱⾟丙→☯
　⿱ 2 件
　 亯 4 [1]
　 羊 5 [2]
　⿱亯羊→☯
　⿰ 2 件
　 戶 3 [1]
　 𠃛 4 [2]
　⿰戶𠃛→☯
　⿸ 2 件
　 尸 4 [1]
　 出 5 [2]
　⿸尸出→☯
　⿰ 2 件
　 戶 3 [1]
　 戈 4 [2]
　⿰戶戈→☯
　⿰ 2 件
　 口 4 [1]
　 口 5 [2]
　⿰口口→☯
　⿸ 2 件
　 戶 3 [1]
　 口 4 [2]
　⿸戶口→☯
　⿰ 2 件
　 斤 3 [1]
　 斤 4 [2]
　⿰斤斤→☯
　⿱ 2 件
　 朿 4 [1]
　 貝 5 [2]
　⿱朿貝→☯
　⿴ 2 件
　 囗 4 [1]
　 玉 5 [2]
　⿴囗玉→☯
　⿱ 2 件
　 冈 4 [1]
　 夕 5 [2]
　⿱冈夕→☯
　⿱ 2 件
　 山 4 [1]
　 石 5 [2]
　⿱山石→☯
　⿰ 2 件
　 日 4 [1]
　 勺 5 [2]
　⿰日勺→☯
　⿱ 2 件
　 宀 4 [1]
　 各 5 [2]
　⿱宀各→☯
　⿱ 2 件
　 日 4 [1]
　 立 5 [2]
　⿱日立→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿱ 2 件
　 此 4 [1]
　 木 5 [2]
　⿱此木→☯
　⿰ 2 件
　 有 4 [1]
　 邑 5 [2]
　⿰有邑→☯
　⿰ 2 件
　 口 3 [1]
　 句 4 [2]
　⿰口句→☯
　⿸ 2 件
　　⿱ 2 件
　　 丶 5 [1]
　　 石 6 [2]
　　⿱丶石→☯
　 ☯ 6 [1]
　 又 7 [2]
　⿸☯又→☯
　⸫ 1 件
　　⿱ 2 件
　　 口 4 [1]
　　 丨 5 [2]
　　⿱口丨→☯
　 ☯ 5 [1]
　⸫☯→☯
　Ｔ 3 件
　 桑 3 [1]
　 口 4 [2]
　 口 5 [3]
　Ｔ桑口口→☯
　⿵ 2 件
　 ⾼ 4 [1]
　 口 5 [2]
　⿵⾼口→☯
　⿸ 2 件
　 厂 4 [1]
　 里 5 [2]
　⿸厂里→☯
　⿱ 2 件
　　⿰ 2 件
　　 火 4 [1]
　　 火 5 [2]
　　⿰火火→☯
　 ☯ 5 [1]
　 乂 6 [2]
　⿱☯乂→☯
　⿰ 2 件
　 口 4 [1]
　 匕 5 [2]
　⿰口匕→☯
　⿱ 2 件
　　⿲ 3 件
　　　⿱ 2 件
　　　 㐅 5 [1]
　　　 㐅 6 [2]
　　　⿱㐅㐅→☯
　　 ☯ 6 [1]
　　 爪 7 [2]
　　 仉 8 [3]
　　⿲☯爪仉→☯
　 ☯ 8 [1]
　 宀 9 [2]
　⿱☯宀→☯
　⸫ 1 件
　 口 3 [1]
　⸫口→☯
　⿰ 2 件
　 峕 3 [1]
　 殳 4 [2]
　⿰峕殳→☯
　⿱ 2 件
　 肉 4 [1]
　 缶 5 [2]
　⿱肉缶→☯
　⿱ 2 件
　 耂 4 [1]
　　⿱ 2 件
　　 匕 6 [1]
　　　⿴ 2 件
　　　 口 8 [1]
　　　 一 9 [2]
　　　⿴口一→☯
　　 ☯ 9 [2]
　　⿱匕☯→☯
　 ☯ 9 [2]
　⿱耂☯→☯
　⿱ 2 件
　 口 3 [1]
　 冊 4 [2]
　⿱口冊→☯
　⿱ 2 件
　 小 4 [1]
　 貝 5 [2]
　⿱小貝→☯
　⿰ 2 件
　 口 4 [1]
　 匕 5 [2]
　⿰口匕→☯
　⿰ 2 件
　 日 4 [1]
　 西 5 [2]
　⿰日西→☯
　⿱ 2 件
　 因 4 [1]
　 心 5 [2]
　⿱因心→☯
　⿱ 2 件
　 今 4 [1]
　 貝 5 [2]
　⿱今貝→☯
　⿵ 2 件
　 帝 4 [1]
　 口 5 [2]
　⿵帝口→☯
　⿱ 2 件
　 口 3 [1]
　 口 4 [2]
　⿱口口→☯
　⿱ 2 件
　 口 7 [1]
　 口 8 [2]
　⿱口口→☯
　⿱ 2 件
　 堇 4 [1]
　 火 5 [2]
　⿱堇火→☯
　⿰ 2 件
　 力 4 [1]
　 口 5 [2]
　⿰力口→☯
　⿱ 2 件
　 山 4 [1]
　 厓 5 [2]
　⿱山厓→☯
　⿴ 2 件
　 囗 4 [1]
　 或 5 [2]
　⿴囗或→☯
　⿵ 2 件
　　⿻ 2 件
　　 宀 4 [1]
　　 八 5 [2]
　　⿻宀八→☯
　 ☯ 5 [1]
　 口 6 [2]
　⿵☯口→☯
　⿱ 2 件
　 匕 8 [1]
　　⿴ 2 件
　　 口 10 [1]
　　 一 11 [2]
　　⿴口一→☯
　 ☯ 11 [2]
　⿱匕☯→☯
　⿰ 2 件
　 者 4 [1]
　　⿱ 2 件
　　 囗 6 [1]
　　 卩 7 [2]
　　⿱囗卩→☯
　 ☯ 7 [2]
　⿰者☯→☯
　⿱ 2 件
　 尚 4 [1]
　 土 5 [2]
　⿱尚土→☯
　⿺ 2 件
　　⿰ 2 件
　　 彳 5 [1]
　　 止 6 [2]
　　⿰彳止→☯
　 ☯ 6 [1]
　　⿱ 2 件
　　 小 8 [1]
　　 一 9 [2]
　　⿱小一→☯
　 ☯ 9 [2]
　⿺☯☯→☯
　⿻ 2 件
　　⿻ 2 件
　　 又 5 [1]
　　 亇 6 [2]
　　⿻又亇→☯
　 ☯ 6 [1]
　 𣶒 7 [2]
　⿻☯𣶒→☯
　⿱ 2 件
　　⿵ 2 件
　　 宀 5 [1]
　　 一 6 [2]
　　⿵宀一→☯
　 ☯ 6 [1]
　　⿰ 2 件
　　 耳 8 [1]
　　 又 9 [2]
　　⿰耳又→☯
　 ☯ 9 [2]
　⿱☯☯→☯
　⿱ 2 件
　 㬰 4 [1]
　 貝 5 [2]
　⿱㬰貝→☯
　⿽ 2 件
　 爪 4 [1]
　 象 5 [2]
　⿽爪象→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿰ 2 件
　 口 7 [1]
　 口 8 [2]
　⿰口口→☯
　⿽ 2 件
　 爪 3 [1]
　 象 4 [2]
　⿽爪象→☯
　⿳ 3 件
　 又 4 [1]
　　⿰ 2 件
　　 仉 6 [1]
　　 㐁 7 [2]
　　⿰仉㐁→☯
　 ☯ 7 [2]
　 寸 8 [3]
　⿳又☯寸→☯
　⿺ 2 件
　　⿱ 2 件
　　 大 5 [1]
　　 羊 6 [2]
　　⿱大羊→☯
　 ☯ 6 [1]
　　⿱ 2 件
　　 彳 8 [1]
　　 止 9 [2]
　　⿱彳止→☯
　 ☯ 9 [2]
　⿺☯☯→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿰ 2 件
　 口 7 [1]
　 口 8 [2]
　⿰口口→☯
　⿱ 2 件
　 音 4 [1]
　 心 5 [2]
　⿱音心→☯
　⿰ 2 件
　 音 4 [1]
　 欠 5 [2]
　⿰音欠→☯
　⿱ 2 件
　 穴 4 [1]
　 音 5 [2]
　⿱穴音→☯
　⿸ 2 件
　　⿸ 2 件
　　 广 5 [1]
　　　⿰ 2 件
　　　 朩 7 [1]
　　　 朩 8 [2]
　　　⿰朩朩→☯
　　 ☯ 8 [2]
　　⿸广☯→☯
　 ☯ 8 [1]
　 幺 9 [2]
　⿸☯幺→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿰ 2 件
　 口 7 [1]
　 口 8 [2]
　⿰口口→☯
　⿱ 2 件
　 黑 4 [1]
　 土 5 [2]
　⿱黑土→☯
　Ｔ 3 件
　 𠒅 4 [1]
　 土 5 [2]
　 攴 6 [3]
　Ｔ𠒅土攴→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿰ 2 件
　 口 7 [1]
　 口 8 [2]
　⿰口口→☯
　⿸ 2 件
　　⿸ 2 件
　　 广 5 [1]
　　　⿰ 2 件
　　　 朩 7 [1]
　　　 朩 8 [2]
　　　⿰朩朩→☯
　　 ☯ 8 [2]
　　⿸广☯→☯
　 ☯ 8 [1]
　 手 9 [2]
　⿸☯手→☯
　⿸ 2 件
　　⿸ 2 件
　　 广 5 [1]
　　　⿰ 2 件
　　　 朩 7 [1]
　　　 朩 8 [2]
　　　⿰朩朩→☯
　　 ☯ 8 [2]
　　⿸广☯→☯
　 ☯ 8 [1]
　　⿸ 2 件
　　 丆 10 [1]
　　 口 11 [2]
　　⿸丆口→☯
　 ☯ 11 [2]
　⿸☯☯→☯
　⿱ 2 件
　　⿲ 3 件
　　　⿱ 2 件
　　　 㐅 5 [1]
　　　 㐅 6 [2]
　　　⿱㐅㐅→☯
　　 ☯ 6 [1]
　　 爪 7 [2]
　　 仉 8 [3]
　　⿲☯爪仉→☯
　 ☯ 8 [1]
　 宀 9 [2]
　⿱☯宀→☯
　Ｙ 3 件
　 口 3 [1]
　 口 4 [2]
　 匕 5 [3]
　Ｙ口口匕→☯
　⿰ 2 件
　　⿱ 2 件
　　 又 8 [1]
　　 口 9 [2]
　　⿱又口→☯
　 ☯ 9 [1]
　　⿱ 2 件
　　 丿 11 [1]
　　 又 12 [2]
　　⿱丿又→☯
　 ☯ 12 [2]
　⿰☯☯→☯
　⿱ 2 件
　 口 3 [1]
　 口 4 [2]
　⿱口口→☯
　⿱ 2 件
　 口 7 [1]
　 口 8 [2]
　⿱口口→☯
　⿰ 2 件
　 口 3 [1]
　 口 4 [2]
　⿰口口→☯
　⿰ 2 件
　 口 7 [1]
　 口 8 [2]
　⿰口口→☯
　⿽ 2 件
　 衣 4 [1]
　　⿱ 2 件
　　 隹 6 [1]
　　 木 7 [2]
　　⿱隹木→☯
　 ☯ 7 [2]
　⿽衣☯→☯
　Ｔ 3 件
　 𠒅 4 [1]
　 土 5 [2]
　 攴 6 [3]
　Ｔ𠒅土攴→☯
　⿱ 2 件
　 堇 3 [1]
　 火 4 [2]
　⿱堇火→☯
　⿱ 2 件
　 壴 6 [1]
　 口 7 [2]
　⿱壴口→☯
　⿱ 2 件
　 竹 4 [1]
　 羅 5 [2]
　⿱竹羅→☯
　⿶ 2 件
　　⿰ 2 件
　　 丶 5 [1]
　　 丶 6 [2]
　　⿰丶丶→☯
　 ☯ 6 [1]
　 乂 7 [2]
　⿶☯乂→☯
　⿱ 2 件
　 人 4 [1]
　 匕 5 [2]
　⿱人匕→☯
　⿱ 2 件
　 八 4 [1]
　 土 5 [2]
　⿱八土→☯
　⿱ 2 件
　 十 4 [1]
　 口 5 [2]
　⿱十口→☯
　⿱ 2 件
　 八 4 [1]
　 方 5 [2]
　⿱八方→☯
　⿳ 3 件
　 釆 4 [1]
　　⿰ 2 件
　　 𠂇 6 [1]
　　 又 7 [2]
　　⿰𠂇又→☯
　 ☯ 7 [2]
　 卩 8 [3]
　⿳釆☯卩→☯
　⿳ 3 件
　 夂 4 [1]
　 囗 5 [2]
　 㐄 6 [3]
　⿳夂囗㐄→☯
　⿱ 2 件
　 厶 4 [1]
　 鼎 5 [2]
　⿱厶鼎→☯
　⿱ 2 件
　 四 4 [1]
　 方 5 [2]
　⿱四方→☯
　⿱ 2 件
　 止 4 [1]
　　⿴ 2 件
　　 衣 6 [1]
　　 〇 7 [2]
　　⿴衣〇→☯
　 ☯ 7 [2]
　⿱止☯→☯
　⿱ 2 件
　 聿 4 [1]
　 者 5 [2]
　⿱聿者→☯
　⿱ 2 件
　 厶 4 [1]
　 㐭 5 [2]
　⿱厶㐭→☯
　⿱ 2 件
　 叀 4 [1]
　　⿹ 2 件
　　 又 6 [1]
　　 一 7 [2]
　　⿹又一→☯
　 ☯ 7 [2]
　⿱叀☯→☯
　⿱ 2 件
　 㬰 4 [1]
　 貝 5 [2]
　⿱㬰貝→☯
　⿱ 2 件
　 罒 4 [1]
　　⿴ 2 件
　　 衣 6 [1]
　　 〇 7 [2]
　　⿴衣〇→☯
　 ☯ 7 [2]
　⿱罒☯→☯
　Ｔ 3 件
　 言 4 [1]
　 糸 5 [2]
　 糸 6 [3]
　Ｔ言糸糸→☯
　⿱ 2 件
　　Ｔ 3 件
　　 言 5 [1]
　　 糸 6 [2]
　　 糸 7 [3]
　　Ｔ言糸糸→☯
　 ☯ 7 [1]
　 木 8 [2]
　⿱☯木→☯
　⿰ 2 件
　 匕 3 [1]
　 匕 4 [2]
　⿰匕匕→☯
　⿰ 2 件
　 臣 3 [1]
　 又 4 [2]
　⿰臣又→☯
　⿸ 2 件
　 厂 4 [1]
　 力 5 [2]
　⿸厂力→☯
　⿰ 2 件
　 阜 3 [1]
　 𠤎 4 [2]
　⿰阜𠤎→☯
　⿻ 2 件
　 宀 3 [1]
　 八 4 [2]
　⿻宀八→☯
　⿸ 2 件
　 广 4 [1]
　 乇 5 [2]
　⿸广乇→☯
　⿱ 2 件
　 卜 4 [1]
　 尸 5 [2]
　⿱卜尸→☯
　⿰ 2 件
　 井 3 [1]
　 刀 4 [2]
　⿰井刀→☯
　⸫ 1 件
　 厶 3 [1]
　⸫厶→☯
　⿺ 2 件
　 大 4 [1]
　　⿱ 2 件
　　 彳 6 [1]
　　 止 7 [2]
　　⿱彳止→☯
　 ☯ 7 [2]
　⿺大☯→☯
　⿱ 2 件
　 上 4 [1]
　 下 5 [2]
　⿱上下→☯
　⿱ 2 件
　 目 4 [1]
　 卩 5 [2]
　⿱目卩→☯
　⿱ 2 件
　 田 4 [1]
　 土 5 [2]
　⿱田土→☯
　⿳ 3 件
　 爪 4 [1]
　 ● 5 [2]
　　⿹ 2 件
　　 又 7 [1]
　　 一 8 [2]
　　⿹又一→☯
　 ☯ 8 [3]
　⿳爪●☯→☯
　⿳ 3 件
　 爪 4 [1]
　 ● 5 [2]
　　⿹ 2 件
　　 又 7 [1]
　　 一 8 [2]
　　⿹又一→☯
　 ☯ 8 [3]
　⿳爪●☯→☯
　⿰ 2 件
　 日 4 [1]
　 寸 5 [2]
　⿰日寸→☯
　⿱ 2 件
　 今 4 [1]
　 心 5 [2]
　⿱今心→☯
　⿵ 2 件
　　Ｔ 3 件
　　 丰 5 [1]
　　 𠂇 6 [2]
　　 又 7 [3]
　　Ｔ丰𠂇又→☯
　 ☯ 7 [1]
　 手 8 [2]
　⿵☯手→☯
　⿱ 2 件
　 木 3 [1]
　 土 4 [2]
　⿱木土→☯
　⿱ 2 件
　 𠀠 3 [1]
　 丌 4 [2]
　⿱𠀠丌→☯
　⿱ 2 件
　 亯 4 [1]
　 羊 5 [2]
　⿱亯羊→☯
　⿵ 2 件
　　⿻ 2 件
　　 宀 4 [1]
　　 八 5 [2]
　　⿻宀八→☯
　 ☯ 5 [1]
　 口 6 [2]
　⿵☯口→☯
　⿰ 2 件
　 方 3 [1]
　 方 4 [2]
　⿰方方→☯
　⿰ 2 件
　 臣 3 [1]
　 又 4 [2]
　⿰臣又→☯
　⿰ 2 件
　 木 3 [1]
　 方 4 [2]
　⿰木方→☯
　⿰ 2 件
　 阜 3 [1]
　 有 4 [2]
　⿰阜有→☯
　⿱ 2 件
　　⿱ 2 件
　　　⿻ 2 件
　　　 八 6 [1]
　　　 十 7 [2]
　　　⿻八十→☯
　　 ☯ 7 [1]
　　　⿰ 2 件
　　　 𠂇 9 [1]
　　　 又 10 [2]
　　　⿰𠂇又→☯
　　 ☯ 10 [2]
　　⿱☯☯→☯
　 ☯ 10 [1]
　 土 11 [2]
　⿱☯土→☯
　⿰ 2 件
　 心 4 [1]
　　⿳ 3 件
　　 一 6 [1]
　　 月 7 [2]
　　 一 8 [3]
　　⿳一月一→☯
　 ☯ 8 [2]
　⿰心☯→☯
　⸫ 1 件
　 土 3 [1]
　⸫土→☯
　⿸ 2 件
　 卩 4 [1]
　 又 5 [2]
　⿸卩又→☯
　⿱ 2 件
　　⿸ 2 件
　　 又 5 [1]
　　 土 6 [2]
　　⿸又土→☯
　 ☯ 6 [1]
　 肉 7 [2]
　⿱☯肉→☯
　⿱ 2 件
　 龱 3 [1]
　　⿰ 2 件
　　　⿱ 2 件
　　　 丶 6 [1]
　　　 丶 7 [2]
　　　⿱丶丶→☯
　　 ☯ 7 [1]
　　　⿱ 2 件
　　　 丶 9 [1]
　　　 丶 10 [2]
　　　⿱丶丶→☯
　　 ☯ 10 [2]
　　⿰☯☯→☯
　 ☯ 10 [2]
　⿱龱☯→☯
　⿱ 2 件
　 四 4 [1]
　 方 5 [2]
　⿱四方→☯
　⿰ 2 件
　　⿱ 2 件
　　 一 5 [1]
　　　⿸ 2 件
　　　 丆 7 [1]
　　　　⿱ 2 件
　　　　 一 9 [1]
　　　　 一 10 [2]
　　　　⿱一一→☯
　　　 ☯ 10 [2]
　　　⿸丆☯→☯
　　 ☯ 10 [2]
　　⿱一☯→☯
　 ☯ 10 [1]
　 殳 11 [2]
　⿰☯殳→☯
　⿱ 2 件
　　Ｔ 3 件
　　 言 5 [1]
　　 糸 6 [2]
　　 糸 7 [3]
　　Ｔ言糸糸→☯
　 ☯ 7 [1]
　 弓 8 [2]
　⿱☯弓→☯
　⿱ 2 件
　　⿰ 2 件
　　 火 4 [1]
　　 火 5 [2]
　　⿰火火→☯
　 ☯ 5 [1]
　 乂 6 [2]
　⿱☯乂→☯
　⿰ 2 件
　 工 4 [1]
　 工 5 [2]
　⿰工工→☯
　⿰ 2 件
　 𠂇 7 [1]
　 又 8 [2]
　⿰𠂇又→☯
　⿰ 2 件
　 水 3 [1]
　 呈 4 [2]
　⿰水呈→☯
　⿳ 3 件
　 人 4 [1]
　 口 5 [2]
　 皿 6 [3]
　⿳人口皿→☯
　⿱ 2 件
　 亠 4 [1]
　　⿱ 2 件
　　 日 6 [1]
　　　⿹ 2 件
　　　 丂 8 [1]
　　　 彡 9 [2]
　　　⿹丂彡→☯
　　 ☯ 9 [2]
　　⿱日☯→☯
　 ☯ 9 [2]
　⿱亠☯→☯
　⿰ 2 件
　 亯 3 [1]
　 丮 4 [2]
　⿰亯丮→☯
　⿳ 3 件
　 亼 4 [1]
　 口 5 [2]
　　⿴ 2 件
　　 口 7 [1]
　　 一 8 [2]
　　⿴口一→☯
　 ☯ 8 [3]
　⿳亼口☯→☯
　⿱ 2 件
　 羊 4 [1]
　 言 5 [2]
　⿱羊言→☯
　⿱ 2 件
　　Ｙ 3 件
　　 爪 5 [1]
　　 仉 6 [2]
　　　⿱ 2 件
　　　 丨 8 [1]
　　　 小 9 [2]
　　　⿱丨小→☯
　　 ☯ 9 [3]
　　Ｙ爪仉☯→☯
　 ☯ 9 [1]
　 貝 10 [2]
　⿱☯貝→☯
　⿰ 2 件
　 阜 3 [1]
　 彖 4 [2]
　⿰阜彖→☯
　⿺ 2 件
　　⿱ 2 件
　　 大 5 [1]
　　 羊 6 [2]
　　⿱大羊→☯
　 ☯ 6 [1]
　　⿱ 2 件
　　 彳 8 [1]
　　 止 9 [2]
　　⿱彳止→☯
　 ☯ 9 [2]
　⿺☯☯→☯
　⿱ 2 件
　　⿰ 2 件
　　 屮 5 [1]
　　 屮 6 [2]
　　⿰屮屮→☯
　 ☯ 6 [1]
　 者 7 [2]
　⿱☯者→☯
　⿲ 3 件
　 予 3 [1]
　 木 4 [2]
　 木 5 [3]
　⿲予木木→☯
　⿱ 2 件
　　⿲ 3 件
　　　⿱ 2 件
　　　 㐅 5 [1]
　　　 㐅 6 [2]
　　　⿱㐅㐅→☯
　　 ☯ 6 [1]
　　 爪 7 [2]
　　 仉 8 [3]
　　⿲☯爪仉→☯
　 ☯ 8 [1]
　 宀 9 [2]
　⿱☯宀→☯
　⸫ 1 件
　 龱 3 [1]
　⸫龱→☯
　⿴ 2 件
　 衣 4 [1]
　　⿱ 2 件
　　 罒 6 [1]
　　 水 7 [2]
　　⿱罒水→☯
　 ☯ 7 [2]
　⿴衣☯→☯
　⸬ 1 件
　 龱 3 [1]
　⸬龱→☯
　⿱ 2 件
　　Ｔ 3 件
　　 言 5 [1]
　　 糸 6 [2]
　　 糸 7 [3]
　　Ｔ言糸糸→☯
　 ☯ 7 [1]
　 弓 8 [2]
　⿱☯弓→☯
　⿱ 2 件
　 士 4 [1]
　 口 5 [2]
　⿱士口→☯
　⿱ 2 件
　 士 4 [1]
　 口 5 [2]
　⿱士口→☯
　⿰ 2 件
　 口 5 [1]
　　⿹ 2 件
　　 又 7 [1]
　　 一 8 [2]
　　⿹又一→☯
　 ☯ 8 [2]
　⿰口☯→☯
　⿰ 2 件
　 口 5 [1]
　　⿹ 2 件
　　 又 7 [1]
　　 一 8 [2]
　　⿹又一→☯
　 ☯ 8 [2]
　⿰口☯→☯
　⿱ 2 件
　 士 4 [1]
　 口 5 [2]
　⿱士口→☯
　Ｔ 3 件
　 言 3 [1]
　 糸 4 [2]
　 糸 5 [3]
　Ｔ言糸糸→☯
　Ｙ 3 件
　 㔿 3 [1]
　 卩 4 [2]
　 土 5 [3]
　Ｙ㔿卩土→☯
　⿲ 3 件
　 言 3 [1]
　 火 4 [2]
　 火 5 [3]
　⿲言火火→☯
　⿲ 3 件
　 𦣻 3 [1]
　 爪 4 [2]
　 仉 5 [3]
　⿲𦣻爪仉→☯
　⿰ 2 件
　 口 4 [1]
　 匕 5 [2]
　⿰口匕→☯
　⿱ 2 件
　 𦭝 3 [1]
　 人 4 [2]
　⿱𦭝人→☯
　⿱ 2 件
　 𦣻 4 [1]
　 卩 5 [2]
　⿱𦣻卩→☯
　⿰ 2 件
　 𠂇 4 [1]
　 又 5 [2]
　⿰𠂇又→☯
　⿹ 2 件
　 𠀀 4 [1]
　 口 5 [2]
　⿹𠀀口→☯
　Ｔ 3 件
　 丰 3 [1]
　 𠂇 4 [2]
　 又 5 [3]
　Ｔ丰𠂇又→☯
　⿰ 2 件
　 𠂇 4 [1]
　 又 5 [2]
　⿰𠂇又→☯
　⿰ 2 件
　 丯 3 [1]
　 刀 4 [2]
　⿰丯刀→☯
　⿱ 2 件
　 ⼣ 4 [1]
　 ⼣ 5 [2]
　⿱⼣⼣→☯
　⸫ 1 件
　 止 4 [1]
　⸫止→☯
　⿻ 2 件
　 大 3 [1]
　 八 4 [2]
　⿻大八→☯
　⿰ 2 件
　 爿 3 [1]
　 ⼣ 4 [2]
　⿰爿⼣→☯
　⿱ 2 件
　 八 3 [1]
　 酉 4 [2]
　⿱八酉→☯
　⿱ 2 件
　 大 4 [1]
　 八 5 [2]
　⿱大八→☯
　⿵ 2 件
　 宀 3 [1]
　 釆 4 [2]
　⿵宀釆→☯
　⿰ 2 件
　 𠂇 6 [1]
　 又 7 [2]
　⿰𠂇又→☯
　⿵ 2 件
　 宀 3 [1]
　 釆 4 [2]
　⿵宀釆→☯
　⿰ 2 件
　 𠂇 6 [1]
　 又 7 [2]
　⿰𠂇又→☯
　⿰ 2 件
　 爿 3 [1]
　　⿱ 2 件
　　 爪 5 [1]
　　　⿹ 2 件
　　　 又 7 [1]
　　　 一 8 [2]
　　　⿹又一→☯
　　 ☯ 8 [2]
　　⿱爪☯→☯
　 ☯ 8 [2]

595       ⿰臣⿱⿸人丶∞口口
1881           ⿸厂豆寸
2741           ⿴囗八面
3918     ▤宀⿰屮屮人⿰屮屮仌
4773           ⿰彐彐又
            ...
35502    ⿱山⿴民⿰⿱丶丶丶丶
35730          ⿱山歸免
35837      ⿱巳丗⿱巛⿻电一
50223        ⿱⿰禾尤⿱咎
61480        ⿺万十⿱彳止
Name: 迩原正解, Length: 91, dtype: object

In [9]:
碼表排序 = 碼表.sort_values(by='漢字', axis=0)
碼表排序["敘數"] = 碼表排序["漢字"].apply(lambda z: 綜敘(z))
碼表排序.loc[碼表排序["漢字"]==碼表排序["迩原正解"], "敘數"] -= 0x100000
# 碼表排序 = 碼表排序.sort_values(by=['漢字'], axis=0, key=攏)
# 碼表排序 = 碼表排序.sort_values(by=['迩原正解'], axis=0, key=依構件排序)
碼表排序 = 碼表排序.sort_values(by='敘數', axis=0)
# 碼表排序 = 碼表排序.sort_values(by=['備註'], axis=0, key=依備註排序)
碼表排序.drop(columns=['敘數'], inplace=True)
碼表排序

,碼位,漢字,迩原正解,迩原或解,迩原別解,迩原又解,異體類型,備註,需說明,字通解字,說文整理番號○表頭意義參見：http://kanji-database.sourceforge.net/ids/ids-analysis.html
472,U+2FBC,⾼,⾼,,,,,高去口,,,
0,U+4E00,一,一,,,,,,,一,0010010
1,U+4E5B,乛,乛,,,,,,,,
2,U+4E01,丁,丁,,,,,,,丁,5160010
3,U+4E02,丂,丂,,,,,,,丂,1540010
...,...,...,...,...,...,...,...,...,...,...,...
74615,U+2B81A,𫠚,,,,,,,,,
74616,U+2B81B,𫠛,,,,,,,,,
74617,U+2B81C,𫠜,,,,,共產,,,→齯,
74618,U+2B81D,𫠝,,,,,,,,,
74619,U+31594,𱖔,⿱屶土,,,,,徵刀,榦,,

In [ ]:
碼表排序.to_excel('碼表有序.xlsx', sheet_name='正表', freeze_panes=(1,0))
# 碼表排序["表頭意義參見：http://kanji-database.sourceforge.net/ids/ids-analysis.html"].any()

In [10]:
# 未列字 = [];有字无解 = []
def 解幹(構字式:str, 全表:pd.DataFrame):
	解式 = ''
	for 字幹 in 構字式:
		if ord(字幹) < 0x3000 or (ord(字幹) >= 0xff00 and ord(字幹) < 0xfff0) or 字幹 == '𝍤':
			解式 += 字幹
			continue
		解字幹 = 全表.loc[全表["漢字"]==字幹, "迩原正解"]
		if len(解字幹) < 1:
			未列字.append(字幹)
			解式 += 字幹;continue
		解字幹 = 解字幹.item()
		if 解字幹 == '':
			有字无解.append(字幹)
			解式 += 字幹
		else:# 不遞歸，在後面迭代，較快
			解式 += 解字幹
	return 解式
# 碼表排序[碼表排序.duplicated('漢字', False)]
迭代一 = 碼表排序["迩原正解"].copy()
碼表排序["迩原正解窮"] = 碼表排序["迩原正解"].apply(lambda x: 解幹(x, 碼表排序))
異條 = 碼表排序["迩原正解窮"] != 迭代一
計數 = 0
while (異條).any():
	迭代一 = 碼表排序["迩原正解窮"].copy()
	碼表排序.loc[異條, "迩原正解窮"] = 碼表排序.loc[異條, "迩原正解窮"].apply(lambda x: 解幹(x, 碼表排序))
	異條 = 碼表排序["迩原正解窮"] != 迭代一
	計數 += 1
	print(f'迭代了 {計數} 次，餘 {len(異條.loc[異條==True])} 條未窮解')
未列字 = list(set(未列字));有字无解 = list(set(有字无解))
未列字數 = len(未列字);无解字數 = len(有字无解)
if 未列字數 > 0:
	print(f'此 {未列字數} 字未列：{"、".join(未列字)}。')
if 无解字數 > 0:
	print(f'此 {无解字數} 字无正解：{"、".join(有字无解)}。')
if 未列字數 > 0 or 无解字數 > 0:
	print(f'請補齊上述 {未列字數+无解字數} 字後再運行。')
else:
	print('蕆。')
差異 = 碼表排序["迩原正解"].compare(碼表排序["迩原正解窮"], result_names=('字幹式','文式'))

print('攺了',str(len(差異)),'條：')
差異

迭代了 1 次，餘 2158 條未窮解
迭代了 2 次，餘 60 條未窮解
迭代了 3 次，餘 0 條未窮解
此 1 字未列：𭁔。
此 1 字无正解：𣐺。
請補齊上述 2 字後再運行。
攺了 24438 條：

       字幹式           文式
599      舉  ⿱⿶牙⿱⿰爪仉⿰𠂇又手
622    ⿱乊乙        ⿱⿱丿八乙
625    ⿰台乚        ⿰⿱㠯口乚
626    ⿰占乚        ⿰⿱卜口乚
628    ⿱加乙        ⿱⿰力口乙
...    ...          ...
71548  ⿱日央        ⿱日⿻冂大
71954  ⿰水配        ⿰水⿰酉㔾
71978  ⿱莫水   ⿱⿳⿰屮屮日⿰屮屮水
72012  ⿰水禀        ⿰水⿱㐭示
73381  ⿰言妥     ⿰⿳一一舌⿱爪女

[24438 rows x 2 columns]

In [33]:
碼表排序.rename(columns={"迩原正解":"正解榦式","迩原正解窮":"迩原正解"},inplace=True)
碼表排序.to_excel('碼表+窮解.xlsx', sheet_name='正表', freeze_panes=(1,0))
碼表排序.columns
#碼表排序.loc[異條==True]

Index(['碼位', '漢字', '正解榦式', '迩原或解', '迩原別解', '迩原又解', '異體類型', '備註', '需說明', '字通解字',
       '說文整理番號○表頭意義參見：http://kanji-database.sourceforge.net/ids/ids-analysis.html',
       '迩原正解'],
      dtype='object')

In [ ]:
# 碼表排序.loc[異條==True]
所有構件 = 碼表排序['迩原正解'].str.cat(sep='') + 碼表排序['迩原或解'].astype(str).str.cat(sep='') + 碼表排序['迩原別解'].astype(str).str.cat(sep='') + 碼表排序['迩原又解'].astype(str).str.cat(sep='')
所有部件 = re.sub('['+(''.join(冓.keys()))+']','',所有構件)
計 = Counter(所有部件)
len(計.keys())

663