In [1]:
from 工具 import *
碼表 = pd.read_excel('碼表.xlsx', '正表')
# 碼表.dropna(subset=["表頭意義參見：http://kanji-database.sourceforge.net/ids/ids-analysis.html"])

In [2]:
迩原碼表 = 飭碼表(碼表)
# 系統字型列 = matplotlib.font_manager.findSystemFonts(fontpaths=None)# https://matplotlib.org/stable/api/font_manager_api.html
# 字型列 = matplotlib.font_manager.get_font_names()
# matplotlib.font_manager.FontProperties('YeMing').get_name()
# print(系統字型列)
有誤者 = 迩原碼表.校覈()

下列 16 字或有宂餘結構符（缺少部件），或順序有誤：噠、徺、觱、㷥、䃨、䃺、䄝、䊳、䜆、䪯、𠝎、𠷲、𡏨、𡏶、𡽧、𤓒
下列 30 字或有宂餘部件（缺少結構符），或順序有誤：偺、喒、寗、彠、愿、揝、瘙、覩、詣、譿、谧、㯎、㲲、䥚、䫗、䴑、𠙲、𠟅、𠪰、𠫁、𠭂、𠭱、𡇛、𡌵、𡠁、𡢩、𡩋、𡬛、𨓒、𨓹

In [3]:
碼表排序 = 迩原碼表.排序()
碼表排序

,碼位,漢字,迩原正解,迩原或解,迩原別解,迩原又解,異體類型,備註,需說明,字通解字,說文整理番號○表頭意義參見：http://kanji-database.sourceforge.net/ids/ids-analysis.html
472,U+2FBC,⾼,⾼,,,,,高去口,,,
0,U+4E00,一,一,,,,,,,一,0010010
1,U+4E5B,乛,乛,,,,,,,,
2,U+4E01,丁,丁,,,,,,,丁,5160010
3,U+4E02,丂,丂,,,,,,,丂,1540010
...,...,...,...,...,...,...,...,...,...,...,...
74615,U+2B81A,𫠚,,,,,,,,,
74616,U+2B81B,𫠛,,,,,,,,,
74617,U+2B81C,𫠜,,,,,共產,,,→齯,
74618,U+2B81D,𫠝,,,,,,,,,
74619,U+31594,𱖔,⿱屶土,,,,,徵刀,榦,,

In [4]:
迩原碼表.迭代解幹()

迭代了 1 次，餘 2080 條未窮解，本次耗時 191.04 秒
迭代了 2 次，餘 60 條未窮解，本次耗時 19.63 秒
迭代了 3 次，餘 0 條未窮解，本次耗時 0.79 秒
此 11 字未列：⾟、⾈、⽔、⼸、⼨、⻦、●、⽮、⾂、⼣、⼗。
此 1 字无正解：𣐺。
請補齊上述 12 字後再運行。
改了 24596 條：

       字幹式           文式
599      舉  ⿱⿶牙⿱⿰爪仉⿰𠂇又手
622    ⿱乊乙        ⿱⿱丿八乙
625    ⿰台乚        ⿰⿱㠯口乚
626    ⿰占乚        ⿰⿱卜口乚
628    ⿱加乙        ⿱⿰力口乙
...    ...          ...
71548  ⿱日央        ⿱日⿻冂大
71954  ⿰水配        ⿰水⿰酉㔾
71978  ⿱莫水   ⿱⿳⿰屮屮日⿰屮屮水
72012  ⿰水禀        ⿰水⿱㐭示
73381  ⿰言妥     ⿰⿳一一舌⿱爪女

[24596 rows x 2 columns]

In [ ]:
迩原碼表.改為擊鍵序()
# 碼表排序.rename(columns={"迩原正解":"正解榦式","迩原正解窮":"迩原正解"},inplace=True)
迩原碼表.碼表.to_excel('碼表+鍵序.xlsx', sheet_name='正表', freeze_panes=(1,0))
迩原碼表.碼表.columns
#碼表排序.loc[異條==True]

Index(['碼位', '漢字', '正解榦式', '迩原或解', '迩原別解', '迩原又解', '異體類型', '備註', '需說明', '字通解字',
       '說文整理番號○表頭意義參見：http://kanji-database.sourceforge.net/ids/ids-analysis.html',
       '迩原正解', '正解鍵', '或解鍵', '別解鍵', '又解鍵'],
      dtype='object')

In [ ]:
## 調試
# from 工具 import *
# 碼表 = pd.read_excel('碼表+鍵序.xlsx', '正表')
# 迩原碼表 = 飭碼表(碼表)
# from matplotlib import font_manager
# font_manager.get_font_names()

In [19]:
統計碼表 = 迩原碼表.統計(False)
末序 = -2
寡文 = [統計碼表["文"].most_common()[-1]]
while 統計碼表["文"].most_common()[末序][1] == 寡文[0][1]:
    寡文.append(統計碼表["文"].most_common()[末序])
    末序 -= 1
print(f'凡 {len(統計碼表["文"])} 个文。\n最頻：{統計碼表["文"].most_common(10)}\n最寡 {len(寡文)} 个，每文 {寡文[0][1]} 現：')
寡文 = list(zip(*寡文))[0]
print('、'.join(寡文))
if len(統計碼表["非文"]) > 0:
    print(f'非正解中出現 {len(統計碼表["非文"])} 个字榦，請繼續解之：')
    print(統計碼表["非文"])

凡 589 个文。
最頻：[('口', 9471), ('一', 9406), ('人', 5799), ('屮', 5579), ('又', 4390), ('木', 2720), ('土', 2545), ('舌', 2457), ('止', 2380), ('水', 2055)]
最寡 25 个，每文 1 現：
𣐺、𦥺、𠔂、𠈒、𠅁、𠄔、𠃎、𠃋、𠂼、𠂭、𨏖、𠦴、甪、甴、甩、𠕄、𠂈、曱、㶫、𡆵、𠙴、𠘧、𤉡、丳、𠁩
非正解中出現 12 个字榦，請繼續解之：
[('番', 1), ('羽', 2), ('央', 1), ('行', 1), ('寸', 2), ('艸', 1), ('㐬', 1), ('夅', 1), ('京', 1), ('品', 1), ('公', 5), ('朐', 1)]